version: '2'

services:
  frontend:
    build: ./frontend
    environment:
      - VIRTUAL_HOST=go-wiki.origin
      - VIRTUAL_PORT=2015
  backend:
    build: ./backend
    environment:
      - VIRTUAL_HOST=api.go-wiki.origin
